CREATE DATABASE SalesERPDAL
GO
USE SalesERPDAL
GO


CREATE TABLE DEPARTMENT
(
DepartmentID int IDENTITY(1,1),
DepartmentName NVARCHAR(50) NOT NULL,
Location NVARCHAR(50) NOT NULL,
CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DepartmentID)
)

INSERT INTO DEPARTMENT (DepartmentName, Location) VALUES ('JAVA', 'TPHCM')
INSERT INTO DEPARTMENT (DepartmentName, Location) VALUES ('WEB PROGRAMMING', 'HANOI')
INSERT INTO DEPARTMENT (DepartmentName, Location) VALUES ('C#', 'TPHCM')
